### ISSUE TITLE
Ask Chair about desktop computers for LLM and system deployment

### ISSUE THREAD

**Issue by doeringi** [doeringi/hubsim#8]
### Hardware Requirements - Llama 2 and Platypus 2

- 7B GPU with at least 10 GB VRAM
- 13B at least GPU RTX 3090 or RTX 4090 
- 70B needs at least 80 GB VRAM of ideally A100 GPU

### Hardware Requirements - Mistral 7B

- at least 24 GB GPU vRAM 

Markus Letz
Tobias Schumacher

- Our project
- There are some computers that we can use?
- How do we get access?
- Can we use them remotely (through SSH)?

**Comment by doeringi** [comment]
Wait for response

**Comment by doeringi** [comment]
@jrupprec  Regarding the response from the chairn, can you reply and schedule a meeting for Monday, 16.10. afternoon? You already know the time that I am available :)

**Comment by jrupprec** [comment]
Requested 2:30 on Monday. Waiting for reply

**Comment by Cuzzie** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Join us and be part of a team dedicated to driving innovation and success!

## How to Apply:
To apply for this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.nschlemm, @pwq1989, @chiehpower, @ronfinn, @hackerchenzhuo, @mahmutyvz, @Gaosc, @railscard, @youen, @Akorede45, @zhongkey123, @lingerun, @mjtpena, @disorn-inc, @theklr, @srvz, @williamteo-st, @dotkim, @biubiupiu123, @TheCukitoDev
